### ISSUE TITLE
Class Property vs local variable has different result.

### ISSUE THREAD

**Issue by jonnywilliamson** [Haehnchen/idea-php-phpunit-plugin#14] opened 2017-06-02 21:26 UTC
I'm not sure if this is a bug, but I just want to highlight something I've come across and wondered if someone could shine some light on it.

If I create a very simple test like the following and generate a prophesize object as a normal variable inside a function, I get full autocomplete working:
![image](https://cloud.githubusercontent.com/assets/2513663/26745318/dd61bcf6-47e1-11e7-9bf5-e55abaccf767.png)

If however I do the exact same thing, only this time create the prophesize object and set it as a property on the class, when I try and access it again, no auto-complete works:

![image](https://cloud.githubusercontent.com/assets/2513663/26745418/51b962b6-47e2-11e7-87d5-ff4c8cfc52d8.png)

Is this intentional? Or is it a limitation of how the plugin works etc?

Thanks for any help/insight into this issue!

**Comment by inwaar** [comment] 2017-06-03 06:50
I've got the same issue with `$this->fake = $this->createMock()` and `$this->fake = $this->createPartialMock()`.

**Comment by overgapo** [comment] 2017-06-06 07:38
duplicate of https://github.com/Haehnchen/idea-php-phpunit-plugin/issues/13

**Comment by jonnywilliamson** [comment] 2017-06-06 07:45
Hmm, must have thought that was something different or I had forgotten about that!

**Comment by Haehnchen** [comment] 2020-04-24 16:06
tested and working; catched also with a test

**Closed by Haehnchen** 2020-04-24 16:06 UTC
